import {
  ArrowUpDownIcon,
  BanIcon,
  BellIcon,
  BookUserIcon,
  BriefcaseBusinessIcon,
  BriefcaseIcon,
  BuildingIcon,
  CalendarClockIcon,
  CalendarIcon,
  ChartBarIcon,
  ChartPieIcon,
  CircleCheckIcon,
  CircleGaugeIcon,
  CircleMinusIcon,
  CirclePauseIcon,
  CircleXIcon,
  ContrastIcon,
  CreditCardIcon,
  DatabaseIcon,
  FileIcon,
  FilePenLineIcon,
  FileTextIcon,
  HandshakeIcon,
  LayersIcon,
  LinkIcon,
  ListIcon,
  LockIcon,
  MailIcon,
  PaperclipIcon,
  PencilIcon,
  PenToolIcon,
  PercentIcon,
  PlugIcon,
  PlusIcon,
  PoundSterlingIcon,
  RocketIcon,
  SearchIcon,
  Share2Icon,
  ShieldHalfIcon,
  SmartphoneIcon,
  SparklesIcon,
  SquareKanbanIcon,
  StarIcon,
  StickyNoteIcon,
  TriangleAlertIcon,
  TypeIcon,
  UserIcon,
  UserPlusIcon,
  UsersIcon,
  VideoIcon,
  WandSparklesIcon,
  type LucideIcon,
} from 'lucide-react';

// Maps the Font Awesome icon names used by Mintlify to lucide-react icons
const icons: Record<string, LucideIcon> = {
  'address-book': BookUserIcon,
  'arrows-up-down': ArrowUpDownIcon,
  ban: BanIcon,
  bell: BellIcon,
  briefcase: BriefcaseIcon,
  building: BuildingIcon,
  calendar: CalendarIcon,
  'calendar-clock': CalendarClockIcon,
  'chart-bar': ChartBarIcon,
  'chart-kanban': SquareKanbanIcon,
  'chart-pie': ChartPieIcon,
  'circle-check': CircleCheckIcon,
  'circle-half-stroke': ContrastIcon,
  'circle-minus': CircleMinusIcon,
  'circle-pause': CirclePauseIcon,
  'circle-three-quarters-stroke': CircleGaugeIcon,
  'circle-xmark': CircleXIcon,
  'credit-card': CreditCardIcon,
  database: DatabaseIcon,
  envelope: MailIcon,
  file: FileIcon,
  'file-lines': FileTextIcon,
  'file-signature': FilePenLineIcon,
  font: TypeIcon,
  handshake: HandshakeIcon,
  'layer-group': LayersIcon,
  link: LinkIcon,
  list: ListIcon,
  lock: LockIcon,
  'magnifying-glass': SearchIcon,
  mobile: SmartphoneIcon,
  'note-sticky': StickyNoteIcon,
  paperclip: PaperclipIcon,
  'pen-nib': PenToolIcon,
  pencil: PencilIcon,
  percent: PercentIcon,
  plug: PlugIcon,
  plus: PlusIcon,
  rocket: RocketIcon,
  'share-nodes': Share2Icon,
  'shield-halved': ShieldHalfIcon,
  sparkles: SparklesIcon,
  star: StarIcon,
  'sterling-sign': PoundSterlingIcon,
  'triangle-exclamation': TriangleAlertIcon,
  user: UserIcon,
  'user-plus': UserPlusIcon,
  'user-tie': BriefcaseBusinessIcon,
  users: UsersIcon,
  video: VideoIcon,
  'wand-magic-sparkles': WandSparklesIcon,
};

export function faIcon(name: string) {
  const Icon = icons[name];
  if (!Icon) {
    console.warn(`[fa-icons] Unknown icon: ${name}`);
    return undefined;
  }
  return <Icon />;
}
